### ISSUE TITLE
Documentation is needed

### ISSUE THREAD

**Issue by fakherhalim** [Yusuf-EMU/ENGgameengine#1]
In order to use this code, we need build and execution environment documentation.
Without that, it will be hard to use this code

**Comment by Yusuf-EMU** [comment]
There is a g++ line on the top of my c++ code, all of the libs can be downloaded with brew, but this repo is outdated, goto https://github.com/Yusuf-EMU/ENGVk for a much faster vulkan based just download the code as a zip unzip it and run it with g++ main.cpp -std=c++17 -oENG -lvulkan -lglfw, or g++ main.cpp -std=c++17 -oENG -lvulkan -lglfw -O2, but if you want to run this repo, the original ENG use g++ main3Dfile.cpp -omain -framework OpenGL -framework GLUT -lfreeimage -O2  when cding into ENG
